version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"
    ignore:
      - dependency-name: "express-jwt"
        versions: ["0.1.3"]
      - dependency-name: "sanitize-html"
        versions: ["1.4.2"]
      - dependency-name: "unzipper"
        versions: ["0.9.15"]
      - dependency-name: "jsonwebtoken"
        versions: ["0.4.0"]
